language: node_js
node_js:
  - "6.1"
  - "6.0"
  - "5.11"
  - "5.10"
  - "5.9"
  - "5.8"
  - "5.7"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
  - "iojs"
git:
  depth: 150
deploy:
  provider: npm
  email: dreadjr@gmail.com
  api_key:
    secure: WQP6U2qXN68IqX7F3/vWDyEH2gMpYvXdrhb07n5n3FuNHYREZ6lMaQVJs3SzU0h3fsSfhQZcoZmlXyHd9FFB/PKpEDKLvzZhkxI9NMtotRtBE4dxzdcqoWcs4Z9PBHL+WBs+JzRqU34LZ5OmDBgN3otQldiYnmXOfYSGasBJy0g=
  on:
    tags: true
    all_branches: true
